#!/usr/bin/env bash
set -euo pipefail

# Usage: ./scripts/release.sh [patch|minor|major]
#
# Bumps the version in all four tracked files that carry it, commits, tags,
# and pushes. Skips ahead automatically if the proposed tag already exists
# locally or on origin.
#
# Files updated:
#   package.json
#   package-lock.json (both top-level "version" AND packages[""].version)
#   src-tauri/Cargo.toml
#   src-tauri/tauri.conf.json
#
# (src-tauri/Cargo.lock is gitignored, so it's regenerated by cargo on build.)
#
# Pre-flight: refuses to run unless we're on main, working tree is clean, and
# local main is in sync with origin/main (auto-pulls if behind, errors on
# divergence). This prevents the "ghost release on stale main" failure mode
# that produced the v0.7.4/v0.7.5 mess.

# --- Pre-flight ---

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [[ "$BRANCH" != "main" ]]; then
  echo "Error: must be on main (currently on '$BRANCH')." >&2
  exit 1
fi

if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "Error: working tree has uncommitted changes. Commit or stash first." >&2
  git status --short >&2
  exit 1
fi

echo "Fetching origin..."
git fetch origin --tags --quiet

LOCAL=$(git rev-parse main)
REMOTE=$(git rev-parse origin/main)
BASE=$(git merge-base main origin/main)

if [[ "$LOCAL" != "$REMOTE" ]]; then
  if [[ "$LOCAL" == "$BASE" ]]; then
    echo "Local main is behind origin/main. Pulling..."
    git pull --rebase origin main
  elif [[ "$REMOTE" == "$BASE" ]]; then
    echo "Local main is ahead of origin/main — releasing your local commits."
  else
    echo "Error: local main and origin/main have diverged. Resolve manually." >&2
    exit 1
  fi
fi

# --- Determine bump type ---

BUMP="${1:-}"
if [[ ! "$BUMP" =~ ^(patch|minor|major)$ ]]; then
  CURRENT=$(node -p "require('./package.json').version")
  IFS='.' read -r MAJ MIN PAT <<< "$CURRENT"
  echo "Current version: $CURRENT"
  echo ""
  echo "  1) patch -> ${MAJ}.${MIN}.$((PAT + 1))"
  echo "  2) minor -> ${MAJ}.$((MIN + 1)).0"
  echo "  3) major -> $((MAJ + 1)).0.0"
  echo ""
  read -rp "Choose [1/2/3]: " choice
  case "$choice" in
    1) BUMP="patch" ;;
    2) BUMP="minor" ;;
    3) BUMP="major" ;;
    *) echo "Invalid choice."; exit 1 ;;
  esac
fi

# --- Compute next version, skipping any tags that already exist ---

CURRENT=$(node -p "require('./package.json').version")
IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"

EXISTING_TAGS=$(
  {
    git tag -l 'v*'
    git ls-remote --tags origin 'v*' 2>/dev/null \
      | awk '{print $2}' \
      | sed 's|refs/tags/||' \
      | grep -v '\^{}$' || true
  } | sort -u
)

apply_bump() {
  case "$1" in
    patch) PATCH=$((PATCH + 1)) ;;
    minor) MINOR=$((MINOR + 1)); PATCH=0 ;;
    major) MAJOR=$((MAJOR + 1)); MINOR=0; PATCH=0 ;;
  esac
}

apply_bump "$BUMP"
# If the requested level collides, fall through to patch bumps until free.
# (e.g. if 0.8.0 is taken on a "minor" request, try 0.8.1, 0.8.2, ...)
while echo "$EXISTING_TAGS" | grep -qx "v${MAJOR}.${MINOR}.${PATCH}"; do
  echo "  v${MAJOR}.${MINOR}.${PATCH} already exists, trying next..."
  apply_bump patch
done

NEW="${MAJOR}.${MINOR}.${PATCH}"
TAG="v${NEW}"
echo "Bumping $CURRENT -> $NEW"

# --- Update version in all five files ---

# package.json + package-lock.json (npm version handles BOTH version fields)
npm version "$NEW" --no-git-tag-version >/dev/null

# src-tauri/Cargo.toml — replace the first version = "..." (the package's own)
sed -i "0,/^version = \".*\"$/s//version = \"$NEW\"/" src-tauri/Cargo.toml

# src-tauri/tauri.conf.json
node -e "
const fs = require('fs');
const f = 'src-tauri/tauri.conf.json';
const conf = JSON.parse(fs.readFileSync(f, 'utf8'));
conf.version = '$NEW';
fs.writeFileSync(f, JSON.stringify(conf, null, 2) + '\n');
"

# --- Commit, tag, push ---

git add package.json package-lock.json \
  src-tauri/Cargo.toml src-tauri/tauri.conf.json
git commit -m "release: ${TAG}"
git tag "$TAG"
git push origin main "$TAG"

echo ""
echo "Released ${TAG} -- CI will build and publish."
